#!/usr/bin/env python
import os
import sys
import argparse


def main(argv=sys.argv):
    parser = argparse.ArgumentParser()
    parser.add_argument('project')
    base_argv = argv[1:2]
    args = parser.parse_args(base_argv)

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{}.settings".format(args.project))

    for_manage_argv = argv[:1] + argv[2:]

    from django.core.management import execute_from_command_line
    execute_from_command_line(for_manage_argv)

if __name__ == "__main__":
    main()
